### PR TITLE
Yt change

### PR DESCRIPTION
**Pull request by yitang**

### CODE REVIEW

**Comment by yitang** [comment]
optomatic is great for tuning hyper-parameters, and it could also be
great for distributing general tasks. The contribution of this PR
includes:
1. remove the part of the code that ties to tuning
   hyper-parameters, which becomes a constraint for general purpose
   tasks. For example, it explicitly requires 'clf', and X, y data as
   input.
2. change some variable/functions name to make it sounds more general
   and less like a library for tuning hyper-parameters.
3. provide a minimal example. It would help to new users to
   understand the relationship _driver_, _worker_, and _user_ concept.
   It can also serve a template for building complex workflow.

Y

**Comment by erlendd** [comment]
Will merge this soon - I need to update the main README.md and the other examples to keep them working. It's a really cool contribution.

**Comment by erlendd** [comment]
Hi @yitang I've been going through this PR but it breaks a lot of things (mainly python 2 compatibility in optomatic/worker.py compute method). I've made you a branch on this repo called yitang, could you resubmit your PR to that branch please?

**Comment by erlendd** [comment]
Manually merged into head.

**Pull request closed without merging**
